executable = ./oft-control/train_controlnet_oft.sh
arguments = $(idx)
exp_name = train_cn_oft
error = ./oft-control/log/$(exp_name).$(Process).err
output = ./oft-control/log/$(exp_name).$(Process).out
log = ./oft-control/log/$(exp_name).$(Process).log

request_memory = 60000
request_disk = 40G
request_cpus = 4
request_gpus = 4
requirements = TARGET.CUDACapability > 7.5 
requirements = TARGET.CUDAGlobalMemoryMb  > 50000

queue 1 idx from seq 0 0 |
